name: gedi_subset
channels:
  - conda-forge
  - defaults
dependencies:
  - backoff
  - black
  - boto3-stubs[s3]
  - botocore-stubs
  - contextily
  - ipykernel
  - isort
  - mypy
  - pre-commit
  - types-cachetools
  - types-requests
